--
-- Add SQL scripts for migrations
--
--

-- Currency vocabulary
INSERT INTO public.vocabulary (id,description,name,topic,url) VALUES (21, 'Currency values for socio-economic datasets', 'Currency vocabulary', 'CURRENCY', 'http://publications.europa.eu/resource/authority/currency');

INSERT INTO public.vocabulary_value (code,extra_data,label,url,vocabulary_id) VALUES 
('ADP', NULL, 'Andorran peseta(until 1999)', 'http://publications.europa.eu/resource/authority/currency/ADP', 21)
,('AED', NULL, 'UAE dirham', 'http://publications.europa.eu/resource/authority/currency/AED', 21)
,('AFA', NULL, 'Afghani(until 2002)', 'http://publications.europa.eu/resource/authority/currency/AFA', 21)
,('AFN', NULL, 'Afghani', 'http://publications.europa.eu/resource/authority/currency/AFN', 21)
,('ALK', NULL, 'Lek(until 1992)', 'http://publications.europa.eu/resource/authority/currency/ALK', 21)
,('ALL', NULL, 'Lek', 'http://publications.europa.eu/resource/authority/currency/ALL', 21)
,('AMD', NULL, 'Dram', 'http://publications.europa.eu/resource/authority/currency/AMD', 21)
,('ANG', NULL, 'Netherlands Antillean guilder', 'http://publications.europa.eu/resource/authority/currency/ANG', 21)
,('AOA', NULL, 'Kwanza', 'http://publications.europa.eu/resource/authority/currency/AOA', 21)
,('AON', NULL, 'New Angolan kwanza(until 1999)', 'http://publications.europa.eu/resource/authority/currency/AON', 21)
,('AOR', NULL, 'Angolan kwanza readjustado(until 1999)', 'http://publications.europa.eu/resource/authority/currency/AOR', 21)
,('ARA', NULL, 'Argentine austral(until 1991)', 'http://publications.europa.eu/resource/authority/currency/ARA', 21)
,('ARM', NULL, 'Argentine peso moneda nacional(until 1969)', 'http://publications.europa.eu/resource/authority/currency/ARM', 21)
,('ARP', NULL, 'Argentine peso argentino(until 1985)', 'http://publications.europa.eu/resource/authority/currency/ARP', 21)
,('ARS', NULL, 'Argentine peso', 'http://publications.europa.eu/resource/authority/currency/ARS', 21)
,('ATS', NULL, 'Austrian schilling(until 1999)', 'http://publications.europa.eu/resource/authority/currency/ATS', 21)
,('AUD', NULL, 'Australian dollar', 'http://publications.europa.eu/resource/authority/currency/AUD', 21)
,('AWG', NULL, 'Aruban guilder', 'http://publications.europa.eu/resource/authority/currency/AWG', 21)
,('AZM', NULL, 'Azerbaijani manat(until 2005)', 'http://publications.europa.eu/resource/authority/currency/AZM', 21)
,('AZN', NULL, 'Azerbaijan manat', 'http://publications.europa.eu/resource/authority/currency/AZN', 21)
,('BAM', NULL, 'Convertible mark', 'http://publications.europa.eu/resource/authority/currency/BAM', 21)
,('BBD', NULL, 'Barbados dollar', 'http://publications.europa.eu/resource/authority/currency/BBD', 21)
,('BDT', NULL, 'Taka', 'http://publications.europa.eu/resource/authority/currency/BDT', 21)
,('BEF', NULL, 'Belgian franc(until 1999)', 'http://publications.europa.eu/resource/authority/currency/BEF', 21)
,('BGJ', NULL, 'Lev A/52(until 1951)', 'http://publications.europa.eu/resource/authority/currency/BGJ', 21)
,('BGK', NULL, 'Lev A/62(until 1961)', 'http://publications.europa.eu/resource/authority/currency/BGK', 21)
,('BGL', NULL, 'Lev A/99(until 1999)', 'http://publications.europa.eu/resource/authority/currency/BGL', 21)
,('BGN', NULL, 'Lev', 'http://publications.europa.eu/resource/authority/currency/BGN', 21)
,('BHD', NULL, 'Bahraini dinar', 'http://publications.europa.eu/resource/authority/currency/BHD', 21)
,('BIF', NULL, 'Burundi franc', 'http://publications.europa.eu/resource/authority/currency/BIF', 21)
,('BMD', NULL, 'Bermuda dollar', 'http://publications.europa.eu/resource/authority/currency/BMD', 21)
,('BND', NULL, 'Brunei dollar', 'http://publications.europa.eu/resource/authority/currency/BND', 21)
,('BOB', NULL, 'Boliviano', 'http://publications.europa.eu/resource/authority/currency/BOB', 21)
,('BOP', NULL, 'Bolivian peso(until 1986)', 'http://publications.europa.eu/resource/authority/currency/BOP', 21)
,('BOV', NULL, 'Mvdol', 'http://publications.europa.eu/resource/authority/currency/BOV', 21)
,('BRB', NULL, 'Cruzeiro novo(until 1985)', 'http://publications.europa.eu/resource/authority/currency/BRB', 21)
,('BRC', NULL, 'Cruzado(until 1989)', 'http://publications.europa.eu/resource/authority/currency/BRC', 21)
,('BRE', NULL, 'Cruziero(until 1993)', 'http://publications.europa.eu/resource/authority/currency/BRE', 21)
,('BRL', NULL, 'Real', 'http://publications.europa.eu/resource/authority/currency/BRL', 21)
,('BRN', NULL, 'Cruzado novo(until 1990)', 'http://publications.europa.eu/resource/authority/currency/BRN', 21)
,('BRR', NULL, 'Cruziero real(until 1993)', 'http://publications.europa.eu/resource/authority/currency/BRR', 21)
,('BRZ', NULL, 'Cruziero(until 1967)', 'http://publications.europa.eu/resource/authority/currency/BRZ', 21)
,('BSD', NULL, 'Bahamian dollar', 'http://publications.europa.eu/resource/authority/currency/BSD', 21)
,('BTN', NULL, 'Ngultrum', 'http://publications.europa.eu/resource/authority/currency/BTN', 21)
,('BWP', NULL, 'Pula', 'http://publications.europa.eu/resource/authority/currency/BWP', 21)
,('BYN', NULL, 'Belarusian rouble', 'http://publications.europa.eu/resource/authority/currency/BYN', 21)
,('BYR', NULL, 'Belarusian rouble(until 2016)', 'http://publications.europa.eu/resource/authority/currency/BYR', 21)
,('BZD', NULL, 'Belize dollar', 'http://publications.europa.eu/resource/authority/currency/BZD', 21)
,('CAD', NULL, 'Canadian dollar', 'http://publications.europa.eu/resource/authority/currency/CAD', 21)
,('CDF', NULL, 'Congolese franc', 'http://publications.europa.eu/resource/authority/currency/CDF', 21)
,('CHE', NULL, 'WIR Euro', 'http://publications.europa.eu/resource/authority/currency/CHE', 21)
,('CHF', NULL, 'Swiss franc', 'http://publications.europa.eu/resource/authority/currency/CHF', 21)
,('CHW', NULL, 'WIR Franc', 'http://publications.europa.eu/resource/authority/currency/CHW', 21)
,('CLE', NULL, 'Chilean escudo(until 1975)', 'http://publications.europa.eu/resource/authority/currency/CLE', 21)
,('CLF', NULL, 'Unidad de Fomento', 'http://publications.europa.eu/resource/authority/currency/CLF', 21)
,('CLP', NULL, 'Chilean peso', 'http://publications.europa.eu/resource/authority/currency/CLP', 21)
,('CNY', NULL, 'Renminbi-yuan', 'http://publications.europa.eu/resource/authority/currency/CNY', 21)
,('COP', NULL, 'Colombian peso', 'http://publications.europa.eu/resource/authority/currency/COP', 21)
,('COU', NULL, 'Unidad de Valor Real', 'http://publications.europa.eu/resource/authority/currency/COU', 21)
,('CRC', NULL, 'Costa Rican colon', 'http://publications.europa.eu/resource/authority/currency/CRC', 21)
,('CSJ', NULL, 'Czechoslovak koruna(until 1953)', 'http://publications.europa.eu/resource/authority/currency/CSJ', 21)
,('CSK', NULL, 'Czechoslovak koruna(until 1993)', 'http://publications.europa.eu/resource/authority/currency/CSK', 21)
,('CUC', NULL, 'Convertible peso', 'http://publications.europa.eu/resource/authority/currency/CUC', 21)
,('CUP', NULL, 'Cuban peso', 'http://publications.europa.eu/resource/authority/currency/CUP', 21)
,('CVE', NULL, 'Cabo Verde escudo', 'http://publications.europa.eu/resource/authority/currency/CVE', 21)
,('CYP', NULL, 'Cypriot pound(until 2007)', 'http://publications.europa.eu/resource/authority/currency/CYP', 21)
,('CZK', NULL, 'Czech koruna', 'http://publications.europa.eu/resource/authority/currency/CZK', 21)
,('DDM', NULL, 'East-German Mark(until 1990)', 'http://publications.europa.eu/resource/authority/currency/DDM', 21)
,('DEM', NULL, 'German mark(until 2001)', 'http://publications.europa.eu/resource/authority/currency/DEM', 21)
,('DJF', NULL, 'Djibouti franc', 'http://publications.europa.eu/resource/authority/currency/DJF', 21)
,('DKK', NULL, 'Danish krone', 'http://publications.europa.eu/resource/authority/currency/DKK', 21)
,('DOP', NULL, 'Dominican peso', 'http://publications.europa.eu/resource/authority/currency/DOP', 21)
,('DZD', NULL, 'Algerian dinar', 'http://publications.europa.eu/resource/authority/currency/DZD', 21)
,('ECS', NULL, 'Ecuadorian sucre(until 2000)', 'http://publications.europa.eu/resource/authority/currency/ECS', 21)
,('EEK', NULL, 'Estonian kroon(until 2010)', 'http://publications.europa.eu/resource/authority/currency/EEK', 21)
,('EGP', NULL, 'Egyptian pound', 'http://publications.europa.eu/resource/authority/currency/EGP', 21)
,('ERN', NULL, 'Nakfa', 'http://publications.europa.eu/resource/authority/currency/ERN', 21)
,('ESP', NULL, 'Peseta(until 1998)', 'http://publications.europa.eu/resource/authority/currency/ESP', 21)
,('ETB', NULL, 'Birr', 'http://publications.europa.eu/resource/authority/currency/ETB', 21)
,('EUR', NULL, 'Euro', 'http://publications.europa.eu/resource/authority/currency/EUR', 21)
,('FIM', NULL, 'Finnish markka(until 1999)', 'http://publications.europa.eu/resource/authority/currency/FIM', 21)
,('FJD', NULL, 'Fiji dollar', 'http://publications.europa.eu/resource/authority/currency/FJD', 21)
,('FKP', NULL, 'Falkland Islands pound', 'http://publications.europa.eu/resource/authority/currency/FKP', 21)
,('FRF', NULL, 'French franc(until 1999)', 'http://publications.europa.eu/resource/authority/currency/FRF', 21)
,('GBP', NULL, 'Pound sterling', 'http://publications.europa.eu/resource/authority/currency/GBP', 21)
,('GEL', NULL, 'Lari', 'http://publications.europa.eu/resource/authority/currency/GEL', 21)
,('GHC', NULL, 'Cedi(until 2006)', 'http://publications.europa.eu/resource/authority/currency/GHC', 21)
,('GHS', NULL, 'Ghana cedi', 'http://publications.europa.eu/resource/authority/currency/GHS', 21)
,('GIP', NULL, 'Gibraltar pound', 'http://publications.europa.eu/resource/authority/currency/GIP', 21)
,('GMD', NULL, 'Dalasi', 'http://publications.europa.eu/resource/authority/currency/GMD', 21)
,('GNE', NULL, 'Syli(until 1985)', 'http://publications.europa.eu/resource/authority/currency/GNE', 21)
,('GNF', NULL, 'Guinean franc', 'http://publications.europa.eu/resource/authority/currency/GNF', 21)
,('GQE', NULL, 'Ekwele(until 1985)', 'http://publications.europa.eu/resource/authority/currency/GQE', 21)
,('GRD', NULL, 'Drachma(until 2000)', 'http://publications.europa.eu/resource/authority/currency/GRD', 21)
,('GTQ', NULL, 'Quetzal', 'http://publications.europa.eu/resource/authority/currency/GTQ', 21)
,('GWP', NULL, 'Guinea-Bissau peso(until 1997)', 'http://publications.europa.eu/resource/authority/currency/GWP', 21)
,('GYD', NULL, 'Guyana dollar', 'http://publications.europa.eu/resource/authority/currency/GYD', 21)
,('HKD', NULL, 'Hong Kong dollar', 'http://publications.europa.eu/resource/authority/currency/HKD', 21)
,('HNL', NULL, 'Lempira', 'http://publications.europa.eu/resource/authority/currency/HNL', 21)
,('HRK', NULL, 'Kuna', 'http://publications.europa.eu/resource/authority/currency/HRK', 21)
,('HTG', NULL, 'Gourde', 'http://publications.europa.eu/resource/authority/currency/HTG', 21)
,('HUF', NULL, 'Forint', 'http://publications.europa.eu/resource/authority/currency/HUF', 21)
,('IDR', NULL, 'Rupiah', 'http://publications.europa.eu/resource/authority/currency/IDR', 21)
,('IEP', NULL, 'Irish pound(until 1999)', 'http://publications.europa.eu/resource/authority/currency/IEP', 21)
,('ILP', NULL, 'Israeli lira(until 1980)', 'http://publications.europa.eu/resource/authority/currency/ILP', 21)
,('ILR', NULL, 'Shekel(until 1985)', 'http://publications.europa.eu/resource/authority/currency/ILR', 21)
,('ILS', NULL, 'Shekel', 'http://publications.europa.eu/resource/authority/currency/ILS', 21)
,('INR', NULL, 'Indian rupee', 'http://publications.europa.eu/resource/authority/currency/INR', 21)
,('IQD', NULL, 'Iraqi dinar', 'http://publications.europa.eu/resource/authority/currency/IQD', 21)
,('IRR', NULL, 'Iranian rial', 'http://publications.europa.eu/resource/authority/currency/IRR', 21)
,('ISJ', NULL, 'Icelandic old króna(until 1981)', 'http://publications.europa.eu/resource/authority/currency/ISJ', 21)
,('ISK', NULL, 'Iceland króna', 'http://publications.europa.eu/resource/authority/currency/ISK', 21)
,('ITL', NULL, 'Italian lira(until 1999)', 'http://publications.europa.eu/resource/authority/currency/ITL', 21)
,('JMD', NULL, 'Jamaica dollar', 'http://publications.europa.eu/resource/authority/currency/JMD', 21)
,('JOD', NULL, 'Jordanian dinar', 'http://publications.europa.eu/resource/authority/currency/JOD', 21)
,('JPY', NULL, 'Yen', 'http://publications.europa.eu/resource/authority/currency/JPY', 21)
,('KES', NULL, 'Kenyan shilling', 'http://publications.europa.eu/resource/authority/currency/KES', 21)
,('KGS', NULL, 'Som', 'http://publications.europa.eu/resource/authority/currency/KGS', 21)
,('KHR', NULL, 'Riel', 'http://publications.europa.eu/resource/authority/currency/KHR', 21)
,('KMF', NULL, 'Comorian franc', 'http://publications.europa.eu/resource/authority/currency/KMF', 21)
,('KPW', NULL, 'North Korean won', 'http://publications.europa.eu/resource/authority/currency/KPW', 21)
,('KRW', NULL, 'South Korean won', 'http://publications.europa.eu/resource/authority/currency/KRW', 21)
,('KWD', NULL, 'Kuwaiti dinar', 'http://publications.europa.eu/resource/authority/currency/KWD', 21)
,('KYD', NULL, 'Cayman Islands dollar', 'http://publications.europa.eu/resource/authority/currency/KYD', 21)
,('KZT', NULL, 'Tenge', 'http://publications.europa.eu/resource/authority/currency/KZT', 21)
,('LAJ', NULL, 'Kip(until 1979)', 'http://publications.europa.eu/resource/authority/currency/LAJ', 21)
,('LAK', NULL, 'Kip', 'http://publications.europa.eu/resource/authority/currency/LAK', 21)
,('LBP', NULL, 'Lebanese pound', 'http://publications.europa.eu/resource/authority/currency/LBP', 21)
,('LKR', NULL, 'Sri Lankan rupee', 'http://publications.europa.eu/resource/authority/currency/LKR', 21)
,('LRD', NULL, 'Liberian dollar', 'http://publications.europa.eu/resource/authority/currency/LRD', 21)
,('LSL', NULL, 'Loti', 'http://publications.europa.eu/resource/authority/currency/LSL', 21)
,('LTL', NULL, 'Litas(until 2014)', 'http://publications.europa.eu/resource/authority/currency/LTL', 21)
,('LUF', NULL, 'Luxembourg franc(until 1999)', 'http://publications.europa.eu/resource/authority/currency/LUF', 21)
,('LVL', NULL, 'Lats(until 2013)', 'http://publications.europa.eu/resource/authority/currency/LVL', 21)
,('LYD', NULL, 'Libyan dinar', 'http://publications.europa.eu/resource/authority/currency/LYD', 21)
,('MAD', NULL, 'Moroccan dirham', 'http://publications.europa.eu/resource/authority/currency/MAD', 21)
,('MDL', NULL, 'Moldovan leu', 'http://publications.europa.eu/resource/authority/currency/MDL', 21)
,('MGA', NULL, 'Ariary', 'http://publications.europa.eu/resource/authority/currency/MGA', 21)
,('MGF', NULL, 'Malagasy franc(until 2004)', 'http://publications.europa.eu/resource/authority/currency/MGF', 21)
,('MKD', NULL, 'Denar', 'http://publications.europa.eu/resource/authority/currency/MKD', 21)
,('MLF', NULL, 'Mali franc(until 1984)', 'http://publications.europa.eu/resource/authority/currency/MLF', 21)
,('MMK', NULL, 'Kyat', 'http://publications.europa.eu/resource/authority/currency/MMK', 21)
,('MNT', NULL, 'Tugrik', 'http://publications.europa.eu/resource/authority/currency/MNT', 21)
,('MOP', NULL, 'Pataca', 'http://publications.europa.eu/resource/authority/currency/MOP', 21)
,('MRO', NULL, 'Ouguiya(until 2018)', 'http://publications.europa.eu/resource/authority/currency/MRO', 21)
,('MRU', NULL, 'Ouguiya', 'http://publications.europa.eu/resource/authority/currency/MRU', 21)
,('MTL', NULL, 'Maltese lira(until 2007)', 'http://publications.europa.eu/resource/authority/currency/MTL', 21)
,('MTP', NULL, 'Maltese pound(until 1971)', 'http://publications.europa.eu/resource/authority/currency/MTP', 21)
,('MUR', NULL, 'Mauritian rupee', 'http://publications.europa.eu/resource/authority/currency/MUR', 21)
,('MVQ', NULL, 'Maldive rupee(until 1983)', 'http://publications.europa.eu/resource/authority/currency/MVQ', 21)
,('MVR', NULL, 'Rufiyaa', 'http://publications.europa.eu/resource/authority/currency/MVR', 21)
,('MWK', NULL, 'Malawian kwacha', 'http://publications.europa.eu/resource/authority/currency/MWK', 21)
,('MXN', NULL, 'Mexican peso', 'http://publications.europa.eu/resource/authority/currency/MXN', 21)
,('MXP', NULL, 'Mexican peso(until 1993)', 'http://publications.europa.eu/resource/authority/currency/MXP', 21)
,('MXV', NULL, 'Mexican Unidad de Inversion', 'http://publications.europa.eu/resource/authority/currency/MXV', 21)
,('MYR', NULL, 'Ringgit', 'http://publications.europa.eu/resource/authority/currency/MYR', 21)
,('MZM', NULL, 'Metica(until 2006)', 'http://publications.europa.eu/resource/authority/currency/MZM', 21)
,('MZN', NULL, 'Metical', 'http://publications.europa.eu/resource/authority/currency/MZN', 21)
,('NAD', NULL, 'Namibian dollar', 'http://publications.europa.eu/resource/authority/currency/NAD', 21)
,('NFD', NULL, 'Newfoundland dollar(until 1949)', 'http://publications.europa.eu/resource/authority/currency/NFD', 21)
,('NGN', NULL, 'Naira', 'http://publications.europa.eu/resource/authority/currency/NGN', 21)
,('NIO', NULL, 'Córdoba oro', 'http://publications.europa.eu/resource/authority/currency/NIO', 21)
,('NLG', NULL, 'Netherlands guilder(until 1998)', 'http://publications.europa.eu/resource/authority/currency/NLG', 21)
,('NOK', NULL, 'Norwegian krone', 'http://publications.europa.eu/resource/authority/currency/NOK', 21)
,('NPR', NULL, 'Nepalese rupee', 'http://publications.europa.eu/resource/authority/currency/NPR', 21)
,('NZD', NULL, 'New Zealand dollar', 'http://publications.europa.eu/resource/authority/currency/NZD', 21)
,('OMR', NULL, 'Omani rial', 'http://publications.europa.eu/resource/authority/currency/OMR', 21)
,('PAB', NULL, 'Balboa', 'http://publications.europa.eu/resource/authority/currency/PAB', 21)
,('PEH', NULL, 'Sol(until 1985)', 'http://publications.europa.eu/resource/authority/currency/PEH', 21)
,('PEI', NULL, 'Inti(until 1991)', 'http://publications.europa.eu/resource/authority/currency/PEI', 21)
,('PEN', NULL, 'Sol', 'http://publications.europa.eu/resource/authority/currency/PEN', 21)
,('PGK', NULL, 'Kina', 'http://publications.europa.eu/resource/authority/currency/PGK', 21)
,('PHP', NULL, 'Philippine peso', 'http://publications.europa.eu/resource/authority/currency/PHP', 21)
,('PKR', NULL, 'Pakistani rupee', 'http://publications.europa.eu/resource/authority/currency/PKR', 21)
,('PLN', NULL, 'Zloty', 'http://publications.europa.eu/resource/authority/currency/PLN', 21)
,('PLZ', NULL, 'Zloty A/94(until 1994)', 'http://publications.europa.eu/resource/authority/currency/PLZ', 21)
,('PTE', NULL, 'Portuguese escudo(until 1999)', 'http://publications.europa.eu/resource/authority/currency/PTE', 21)
,('PYG', NULL, 'Guaraní', 'http://publications.europa.eu/resource/authority/currency/PYG', 21)
,('QAR', NULL, 'Qatari rial', 'http://publications.europa.eu/resource/authority/currency/QAR', 21)
,('ROL', NULL, 'Romanian leu A/05(until 2005)', 'http://publications.europa.eu/resource/authority/currency/ROL', 21)
,('RON', NULL, 'Romanian leu', 'http://publications.europa.eu/resource/authority/currency/RON', 21)
,('RSD', NULL, 'Serbian dinar', 'http://publications.europa.eu/resource/authority/currency/RSD', 21)
,('RUB', NULL, 'Russian rouble', 'http://publications.europa.eu/resource/authority/currency/RUB', 21)
,('RUR', NULL, 'Russian rouble A/97(until 1997)', 'http://publications.europa.eu/resource/authority/currency/RUR', 21)
,('RWF', NULL, 'Rwandese franc', 'http://publications.europa.eu/resource/authority/currency/RWF', 21)
,('SAR', NULL, 'Saudi riyal', 'http://publications.europa.eu/resource/authority/currency/SAR', 21)
,('SBD', NULL, 'Solomon Islands dollar', 'http://publications.europa.eu/resource/authority/currency/SBD', 21)
,('SCR', NULL, 'Seychelles rupee', 'http://publications.europa.eu/resource/authority/currency/SCR', 21)
,('SDD', NULL, 'Sudanese dinar(until 2007)', 'http://publications.europa.eu/resource/authority/currency/SDD', 21)
,('SDG', NULL, 'Sudanese pound', 'http://publications.europa.eu/resource/authority/currency/SDG', 21)
,('SEK', NULL, 'Swedish krona', 'http://publications.europa.eu/resource/authority/currency/SEK', 21)
,('SGD', NULL, 'Singapore dollar', 'http://publications.europa.eu/resource/authority/currency/SGD', 21)
,('SHP', NULL, 'Saint Helena pound', 'http://publications.europa.eu/resource/authority/currency/SHP', 21)
,('SIT', NULL, 'Slovenian tolar(until 2007)', 'http://publications.europa.eu/resource/authority/currency/SIT', 21)
,('SKK', NULL, 'Slovak koruna(until 2009)', 'http://publications.europa.eu/resource/authority/currency/SKK', 21)
,('SLL', NULL, 'Leone', 'http://publications.europa.eu/resource/authority/currency/SLL', 21)
,('SOS', NULL, 'Somali shilling', 'http://publications.europa.eu/resource/authority/currency/SOS', 21)
,('SRD', NULL, 'Surinamese dollar', 'http://publications.europa.eu/resource/authority/currency/SRD', 21)
,('SRG', NULL, 'Suriname guilder(until 2004)', 'http://publications.europa.eu/resource/authority/currency/SRG', 21)
,('SSP', NULL, 'South Sudanese pound', 'http://publications.europa.eu/resource/authority/currency/SSP', 21)
,('STD', NULL, 'Dobra(until 2018)', 'http://publications.europa.eu/resource/authority/currency/STD', 21)
,('STN', NULL, 'Dobra', 'http://publications.europa.eu/resource/authority/currency/STN', 21)
,('SUR', NULL, 'Soviet Union rouble(until 1991)', 'http://publications.europa.eu/resource/authority/currency/SUR', 21)
,('SVC', NULL, 'Salvadorian colón', 'http://publications.europa.eu/resource/authority/currency/SVC', 21)
,('SYP', NULL, 'Syrian pound', 'http://publications.europa.eu/resource/authority/currency/SYP', 21)
,('SZL', NULL, 'Lilangeni', 'http://publications.europa.eu/resource/authority/currency/SZL', 21)
,('THB', NULL, 'Baht', 'http://publications.europa.eu/resource/authority/currency/THB', 21)
,('TJR', NULL, 'Tajikistani rouble(until 2000)', 'http://publications.europa.eu/resource/authority/currency/TJR', 21)
,('TJS', NULL, 'Somoni', 'http://publications.europa.eu/resource/authority/currency/TJS', 21)
,('TMM', NULL, 'Turkmen manat(until 2008)', 'http://publications.europa.eu/resource/authority/currency/TMM', 21)
,('TMT', NULL, 'Turkmen manat', 'http://publications.europa.eu/resource/authority/currency/TMT', 21)
,('TND', NULL, 'Tunisian dinar', 'http://publications.europa.eu/resource/authority/currency/TND', 21)
,('TOP', NULL, 'Paanga', 'http://publications.europa.eu/resource/authority/currency/TOP', 21)
,('TPE', NULL, 'Portuguese Timorese escudo(until 1976)', 'http://publications.europa.eu/resource/authority/currency/TPE', 21)
,('TRL', NULL, 'Turkish lira A/05(until 2005)', 'http://publications.europa.eu/resource/authority/currency/TRL', 21)
,('TRY', NULL, 'Turkish lira', 'http://publications.europa.eu/resource/authority/currency/TRY', 21)
,('TTD', NULL, 'Trinidad and Tobago dollar', 'http://publications.europa.eu/resource/authority/currency/TTD', 21)
,('TWD', NULL, 'New Taiwan dollar', 'http://publications.europa.eu/resource/authority/currency/TWD', 21)
,('TZS', NULL, 'Tanzanian shilling', 'http://publications.europa.eu/resource/authority/currency/TZS', 21)
,('UAH', NULL, 'Hryvnia', 'http://publications.europa.eu/resource/authority/currency/UAH', 21)
,('UAK', NULL, 'Karbovanets(until 1996)', 'http://publications.europa.eu/resource/authority/currency/UAK', 21)
,('UGS', NULL, 'Uganda shilling A/87(until 1987)', 'http://publications.europa.eu/resource/authority/currency/UGS', 21)
,('UGX', NULL, 'Uganda shilling', 'http://publications.europa.eu/resource/authority/currency/UGX', 21)
,('USD', NULL, 'US dollar', 'http://publications.europa.eu/resource/authority/currency/USD', 21)
,('USN', NULL, 'US dollar', 'http://publications.europa.eu/resource/authority/currency/USN', 21)
,('USS', NULL, 'US dollar(until 2014)', 'http://publications.europa.eu/resource/authority/currency/USS', 21)
,('UYI', NULL, 'Uruguay Peso en Unidades Indexadas', 'http://publications.europa.eu/resource/authority/currency/UYI', 21)
,('UYN', NULL, 'Uruguay old peso(until 1993)', 'http://publications.europa.eu/resource/authority/currency/UYN', 21)
,('UYU', NULL, 'Uruguayan peso', 'http://publications.europa.eu/resource/authority/currency/UYU', 21)
,('UYW', NULL, 'Unidad Previsional', 'http://publications.europa.eu/resource/authority/currency/UYW', 21)
,('UZS', NULL, 'Sum', 'http://publications.europa.eu/resource/authority/currency/UZS', 21)
,('VEB', NULL, 'Bolívar fuerte(until 2007)', 'http://publications.europa.eu/resource/authority/currency/VEB', 21)
,('VEF', NULL, 'Bolívar(until 2018)', 'http://publications.europa.eu/resource/authority/currency/VEF', 21)
,('VES', NULL, 'Bolívar soberano', 'http://publications.europa.eu/resource/authority/currency/VES', 21)
,('VNC', NULL, 'Old dong(until 1978)', 'http://publications.europa.eu/resource/authority/currency/VNC', 21)
,('VND', NULL, 'Dong', 'http://publications.europa.eu/resource/authority/currency/VND', 21)
,('VUV', NULL, 'Vatu', 'http://publications.europa.eu/resource/authority/currency/VUV', 21)
,('WST', NULL, 'Tala', 'http://publications.europa.eu/resource/authority/currency/WST', 21)
,('XAF', NULL, 'CFA franc (BEAC)', 'http://publications.europa.eu/resource/authority/currency/XAF', 21)
,('XAG', NULL, 'Silver', 'http://publications.europa.eu/resource/authority/currency/XAG', 21)
,('XAU', NULL, 'Gold', 'http://publications.europa.eu/resource/authority/currency/XAU', 21)
,('XBA', NULL, 'Bond Markets Unit European Composite Unit (EURCO)', 'http://publications.europa.eu/resource/authority/currency/XBA', 21)
,('XBB', NULL, 'Bond Markets Unit European Monetary Unit (E.M.U.-6)', 'http://publications.europa.eu/resource/authority/currency/XBB', 21)
,('XBC', NULL, 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', 'http://publications.europa.eu/resource/authority/currency/XBC', 21)
,('XBD', NULL, 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', 'http://publications.europa.eu/resource/authority/currency/XBD', 21)
,('XCD', NULL, 'East Caribbean dollar', 'http://publications.europa.eu/resource/authority/currency/XCD', 21)
,('XDR', NULL, 'SDR (Special Drawing Right)', 'http://publications.europa.eu/resource/authority/currency/XDR', 21)
,('XEU', NULL, 'European Currency Unit(until 1999)', 'http://publications.europa.eu/resource/authority/currency/XEU', 21)
,('XOF', NULL, 'CFA Franc (BCEAO)', 'http://publications.europa.eu/resource/authority/currency/XOF', 21)
,('XPD', NULL, 'Palladium', 'http://publications.europa.eu/resource/authority/currency/XPD', 21)
,('XPF', NULL, 'CFP franc', 'http://publications.europa.eu/resource/authority/currency/XPF', 21)
,('XPT', NULL, 'Platinum', 'http://publications.europa.eu/resource/authority/currency/XPT', 21)
,('XSU', NULL, 'Sucre', 'http://publications.europa.eu/resource/authority/currency/XSU', 21)
,('XTS', NULL, 'Code reserved for testing purposes', 'http://publications.europa.eu/resource/authority/currency/XTS', 21)
,('XUA', NULL, 'ADB Unit of Account', 'http://publications.europa.eu/resource/authority/currency/XUA', 21)
,('XXX', NULL, 'No currency', 'http://publications.europa.eu/resource/authority/currency/XXX', 21)
,('YDD', NULL, 'South Yemeni dinar(until 1996)', 'http://publications.europa.eu/resource/authority/currency/YDD', 21)
,('YER', NULL, 'Yemeni rial', 'http://publications.europa.eu/resource/authority/currency/YER', 21)
,('YUD', NULL, 'Yugoslav dinar(until 1989)', 'http://publications.europa.eu/resource/authority/currency/YUD', 21)
,('YUF', NULL, 'Yugoslav dinar(until 1965)', 'http://publications.europa.eu/resource/authority/currency/YUF', 21)
,('YUM', NULL, 'Yugoslav dinar(until 2003)', 'http://publications.europa.eu/resource/authority/currency/YUM', 21)
,('YUN', NULL, 'Yugoslav dinar(until 1992)', 'http://publications.europa.eu/resource/authority/currency/YUN', 21)
,('YUS', NULL, 'Yugoslav dinar(until 1943)', 'http://publications.europa.eu/resource/authority/currency/YUS', 21)
,('ZAR', NULL, 'Rand', 'http://publications.europa.eu/resource/authority/currency/ZAR', 21)
,('ZMK', NULL, 'Zambian kwacha(until 2012)', 'http://publications.europa.eu/resource/authority/currency/ZMK', 21)
,('ZMW', NULL, 'Zambian kwacha', 'http://publications.europa.eu/resource/authority/currency/ZMW', 21)
,('ZRN', NULL, 'Zaïrean zaïre(until 1997)', 'http://publications.europa.eu/resource/authority/currency/ZRN', 21)
,('ZRZ', NULL, 'Zaïrean new zaïre(until 1992)', 'http://publications.europa.eu/resource/authority/currency/ZRZ', 21)
,('ZWC', NULL, 'Rhodesian dollar(until 1980)', 'http://publications.europa.eu/resource/authority/currency/ZWC', 21)
,('ZWD', NULL, 'Zimbabwe dollar A/06(until 2006)', 'http://publications.europa.eu/resource/authority/currency/ZWD', 21)
,('ZWL', NULL, 'Zimbabwe dollar', 'http://publications.europa.eu/resource/authority/currency/ZWL', 21)
,('ZWN', NULL, 'Zimbabwe dollar A/08(until 2008)', 'http://publications.europa.eu/resource/authority/currency/ZWN', 21)
,('ZWR', NULL, 'Zimbabwe dollar A/09(until 2009)', 'http://publications.europa.eu/resource/authority/currency/ZWR', 21);


-- Size unit vocabulary
INSERT INTO public.vocabulary (id,description,name,topic,url) VALUES (22, 'Measurement units for dataset variable size unit values', 'Eionet size unit vocabulary', 'SIZE_UNIT', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/');

INSERT INTO public.vocabulary_value (code,extra_data,label,url,vocabulary_id) VALUES 
('NR', NULL, 'Number', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/NR', 22)
,('NR_HAB', NULL, 'Number per inhabitant', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/NR_HAB', 22)
,('THS', NULL, 'Thousand', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS', 22)
,('MIO', NULL, 'Million', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO', 22)
,('BN', NULL, 'Billion', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/BN', 22)
,('HAB', NULL, 'Inhabitant/person/capita', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/HAB', 22)
,('HAB_KM2', NULL, 'Inhabitants per square kilometre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/HAB_KM2', 22)
,('EUR_KG', NULL, 'Euro per kilogram', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/EUR_KG', 22)
,('EUR_HA', NULL, 'Euro per hectare', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/EUR_HA', 22)
,('EUR_HAB', NULL, 'Euro per inhabitant', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/EUR_HAB', 22)
,('EUR_HAB_EU', NULL, 'Euro per inhabitant in percentage of the EU average', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/EUR_HAB_EU', 22)
,('NAC_HA', NULL, 'National currency per hectare', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/NAC_HA', 22)
,('NAC_HAB', NULL, 'National currency per inhabitant', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/NAC_HAB', 22)
,('PPS_KG', NULL, 'Purchasing power standard (PPS) per kilogram', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PPS_KG', 22)
,('PPS_HAB', NULL, 'Purchasing power standard (PPS) per inhabitant', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PPS_HAB', 22)
,('PPS_HAB_EU', NULL, 'Purchasing power standard (PPS) per inhabitant in percentage of the EU average', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PPS_HAB_EU', 22)
,('EUR', NULL, 'Euro', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/EUR', 22)
,('THS_EUR', NULL, 'Thousand euro', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_EUR', 22)
,('MIO_EUR', NULL, 'Million euro', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_EUR', 22)
,('BN_EUR', NULL, 'Billion euro', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/BN_EUR', 22)
,('CT', NULL, 'Euro cent', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/CT', 22)
,('ECU', NULL, 'European currency unit (Ecu)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/ECU', 22)
,('NAC', NULL, 'National currency', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/NAC', 22)
,('THS_NAC', NULL, 'Thousand units of national currency', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_NAC', 22)
,('MIO_NAC', NULL, 'Million units of national currency', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_NAC', 22)
,('BN_NAC', NULL, 'Billion units of national currency', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/BN_NAC', 22)
,('NAT', NULL, 'National currency (former currencies of the euro area countries)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/NAT', 22)
,('MIO_NAT', NULL, 'Million units of national currency (former currencies of the euro area countries)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_NAT', 22)
,('PPS', NULL, 'Purchasing power standard (PPS)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PPS', 22)
,('PPS_HAB_KP05', NULL, 'Purchasing power standard (PPS) per inhabitant at constant 2005 prices', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PPS_HAB_KP05', 22)
,('MIO_PPS', NULL, 'Million purchasing power standards (PPS)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_PPS', 22)
,('MIO_PPS_KP00', NULL, 'Million purchasing power standards (PPS) at 2000 prices', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_PPS_KP00', 22)
,('MIO_PPS_KP05', NULL, 'Million purchasing power standards (PPS) at 2005 prices', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_PPS_KP05', 22)
,('PPCS_HAB', NULL, 'Purchasing power standard based on final consumption per inhabitant', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PPCS_HAB', 22)
,('T', NULL, 'Tonne', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/T', 22)
,('T_HAB', NULL, 'Tonnes per capita', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/T_HAB', 22)
,('THS_T', NULL, 'Thousand tonnes', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_T', 22)
,('KG_HAB', NULL, 'Kilograms per capita', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KG_HAB', 22)
,('TPW', NULL, 'Tonnes product weight', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TPW', 22)
,('TLW', NULL, 'Tonnes live weight', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TLW', 22)
,('MIO_T', NULL, 'Million tonnes', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_T', 22)
,('EUR_T', NULL, 'Euro per tonne', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/EUR_T', 22)
,('NAC_T', NULL, 'National currency per tonne', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/NAC_T', 22)
,('T_HA', NULL, 'Tonnes per hectare', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/T_HA', 22)
,('KTOE', NULL, 'Thousand tonnes of oil equivalent (TOE)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KTOE', 22)
,('MTOE', NULL, 'Million tonnes of oil equivalent (TOE)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MTOE', 22)
,('GT', NULL, 'Gross tonnage (GT)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/GT', 22)
,('THS_GT', NULL, 'Gross tonnage (GT) in thousand', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_GT', 22)
,('MIO_GTKM', NULL, 'Million gross tonne-kilometres', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_GTKM', 22)
,('THS_TKM', NULL, 'Thousand tonne-kilometre (TKM)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_TKM', 22)
,('MIO_TKM', NULL, 'Million tonne-kilometre (TKM)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_TKM', 22)
,('MIO_PKM', NULL, 'Millions of passenger-kilometres', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_PKM', 22)
,('PC', NULL, 'Percentage', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC', 22)
,('PC_AREA', NULL, 'Percentage of area', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_AREA', 22)
,('PC_POP', NULL, 'Percentage of total population', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_POP', 22)
,('PC_ACT', NULL, 'Percentage of active population', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ACT', 22)
,('PC_ACT_HC', NULL, 'Percentage of active population - numerator in head count (HC)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ACT_HC', 22)
,('PC_ACT_FTE', NULL, 'Percentage of active population - numerator in full-time equivalent (FTE)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ACT_FTE', 22)
,('PC_INAC', NULL, 'Percentage of inactive population', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_INAC', 22)
,('PC_EMP', NULL, 'Percentage of total employment', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EMP', 22)
,('PC_EMP_HC', NULL, 'Percentage of total employment - numerator in head count (HC)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EMP_HC', 22)
,('PC_EMP_FTE', NULL, 'Percentage of total employment - numerator in full-time equivalent (FTE)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EMP_FTE', 22)
,('PC_GDP', NULL, 'Percentage of gross domestic product (GDP)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_GDP', 22)
,('PC_BEN', NULL, 'Percentage of total benefits', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_BEN', 22)
,('PC_EXP', NULL, 'Percentage of total expenditure', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EXP', 22)
,('PC_REC', NULL, 'Percentage of total receipts', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_REC', 22)
,('PC_CHE', NULL, 'Percentual share of total current health expenditure (CHE)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_CHE', 22)
,('PC_WRL', NULL, 'Percentage of world total', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_WRL', 22)
,('PC_TOT', NULL, 'Percentage of total', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_TOT', 22)
,('PC_TAX', NULL, 'Percentage of total taxation', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_TAX', 22)
,('PC_HH', NULL, 'Percentage of households', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_HH', 22)
,('PC_EMP_CUSE', NULL, 'Percentage of persons employed using a computer', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EMP_CUSE', 22)
,('PC_EMP_IACC', NULL, 'Percentage of persons employed working in an enterprise with internet access', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EMP_IACC', 22)
,('PC_ENT', NULL, 'Percentage of enterprises', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT', 22)
,('PC_ENT_CUSE', NULL, 'Percentage of the enterprises which use a computer', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_CUSE', 22)
,('PC_ENT_IACC', NULL, 'Percentage of the enterprises with internet access', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_IACC', 22)
,('PC_ENT_ISELL', NULL, 'Percentage of the enterprises which sold over the internet over the last calendar year', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_ISELL', 22)
,('PC_TURN', NULL, 'Percentage of turnover', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_TURN', 22)
,('PC_HH_IACC', NULL, 'Percentage of households with internet access at home', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_HH_IACC', 22)
,('PC_IND', NULL, 'Percentage of individuals', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND', 22)
,('PC_IND_C3', NULL, 'Percentage of individuals who used a computer within the last 3 months', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_C3', 22)
,('PC_IND_ILT12', NULL, 'Percentage of individuals who used internet within the last year', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_ILT12', 22)
,('PC_IND_IU3', NULL, 'Percentage of individuals who used internet in the last 3 months', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_IU3', 22)
,('PC_IND_CTMT3YX', NULL, 'Percentage of individuals who have taken a computer course more than 3 years ago or never', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_CTMT3YX', 22)
,('PC_IND_CIANY', NULL, 'Percentage of individuals who have done at least one of the listed computer or internet activities', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_CIANY', 22)
,('PC_PNT', NULL, 'Percentage point', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_PNT', 22)
,('PC_ENT_IBUY', NULL, 'Percentage of enterprises which purchased over the internet over the last calendar year', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_IBUY', 22)
,('PC_ENT_PURCH', NULL, 'Percentage of total purchases', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_PURCH', 22)
,('PC_ENT_OBUY', NULL, 'Percentage of enterprises which purchased over networks other than the internet over the last calendar year', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_OBUY', 22)
,('PC_ENT_OSELL', NULL, 'Percentage of enterprises which sold over networks other than the internet over the last calendar year', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_OSELL', 22)
,('PC_ENT_ITSPRCR', NULL, 'Percentage of enterprises which recruited or tried to recruit personnel for jobs requiring ICT specialist skills', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_ITSPRCR', 22)
,('PC_ENT_ITSPRCR2', NULL, 'Percentage of enterprises which recruited / tried to recruit personnel for jobs requiring ICT specialist skills (reduced comparability with 2007)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_ITSPRCR2', 22)
,('PC_ENT_ITSPVAC', NULL, 'Percentage of enterprises which had hard-to-fill vacancies for jobs requiring ICT specialist skills', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_ITSPVAC', 22)
,('PC_ENT_ITUSRCR', NULL, 'Percentage of enterprises which recruited or tried to recruit personnel for jobs requiring skills in the use of ICT', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_ITUSRCR', 22)
,('PC_VAL_ISELL', NULL, 'Percentage of internet sales', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_VAL_ISELL', 22)
,('PC_FAT', NULL, 'Fat content (% of product weight)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_FAT', 22)
,('PC_PRO', NULL, 'Protein content (% of product weight)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_PRO', 22)
,('PC_TOT_HAB', NULL, 'Percentage of total (based on inhabitants)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_TOT_HAB', 22)
,('PC_TOT_FTE', NULL, 'Percentage of total (based on full-time equivalents)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_TOT_FTE', 22)
,('PC_TOT_JOB', NULL, 'Percentage of total (based on jobs)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_TOT_JOB', 22)
,('PCH_PRE', NULL, 'Percentage change on previous period', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_PRE', 22)
,('PCH_SM', NULL, 'Percentage change compared to same period in previous year', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_SM', 22)
,('PCH_PRE_HAB', NULL, 'Percentage change on previous period (based on inhabitants)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_PRE_HAB', 22)
,('PCH_PRE_FTE', NULL, 'Percentage change on previous period (based on full-time equivalents)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_PRE_FTE', 22)
,('PCH_PRE_JOB', NULL, 'Percentage change on previous period (based on jobs)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_PRE_JOB', 22)
,('AVG', NULL, 'Average', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/AVG', 22)
,('MV12R', NULL, 'Moving 12-months average rate of change', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MV12R', 22)
,('RT', NULL, 'Rate', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT', 22)
,('CVA', NULL, 'Coefficient of variation for absolute value', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/CVA', 22)
,('I_MED', NULL, 'Income index (compared to national median)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/I_MED', 22)
,('I_MEAN', NULL, 'Income index (compared to national mean)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/I_MEAN', 22)
,('M', NULL, 'Metre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/M', 22)
,('M2', NULL, 'Square metre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/M2', 22)
,('M3', NULL, 'Cubic metre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/M3', 22)
,('THS_M3', NULL, 'Thousand cubic metres', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_M3', 22)
,('MIO_M3', NULL, 'Million cubic metres', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_M3', 22)
,('M3_HAB', NULL, 'Cubic metres per inhabitant', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/M3_HAB', 22)
,('KM', NULL, 'Kilometre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KM', 22)
,('KM2', NULL, 'Square kilometre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KM2', 22)
,('HA', NULL, 'Hectare', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/HA', 22)
,('THS_HA', NULL, 'Thousand hectares', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_HA', 22)
,('TEU', NULL, 'Twenty-foot equivalent unit (TEU)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TEU', 22)
,('THS_TEU', NULL, 'Thousand twenty-foot equivalent unit (TEU)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_TEU', 22)
,('G_PKM', NULL, 'Grams per passenger-kilometre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/G_PKM', 22)
,('G_TKM', NULL, 'Grams per tonne-kilometre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/G_TKM', 22)
,('KG', NULL, 'Kilogram', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KG', 22)
,('L', NULL, 'Litre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/L', 22)
,('THS_HL', NULL, 'Thousand hectolitres', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_HL', 22)
,('OZ', NULL, 'Ounce', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/OZ', 22)
,('KW', NULL, 'Kilowatt', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KW', 22)
,('MW', NULL, 'Megawatt', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MW', 22)
,('GW', NULL, 'Gigawatt', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/GW', 22)
,('KWH', NULL, 'Kilowatt-hour', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KWH', 22)
,('GWH', NULL, 'Gigawatt-hour', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/GWH', 22)
,('KCAL', NULL, 'Kilocalorie', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KCAL', 22)
,('TJ', NULL, 'Terajoule', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TJ', 22)
,('TJ_GCV', NULL, 'Terajoule (gross calorific value - GCV)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TJ_GCV', 22)
,('GJ_GCV', NULL, 'Gigajoule (gross calorific value - GCV)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/GJ_GCV', 22)
,('MN', NULL, 'Minute', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MN', 22)
,('THS_MN', NULL, 'Thousand minutes', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_MN', 22)
,('HR', NULL, 'Hour', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/HR', 22)
,('DAY', NULL, 'Day', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/DAY', 22)
,('MTH', NULL, 'Month', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MTH', 22)
,('YR', NULL, 'Year', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/YR', 22)
,('HD', NULL, 'Head (animal)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/HD', 22)
,('THS_HD', NULL, 'Thousand heads (animals)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_HD', 22)
,('AWU', NULL, 'Annual working unit (AWU)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/AWU', 22)
,('THS_AWU', NULL, 'Thousand annual working units (AWU)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_AWU', 22)
,('MACH', NULL, 'Machine', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MACH', 22)
,('LSU', NULL, 'Livestock unit (LSU)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/LSU', 22)
,('HC', NULL, 'Head count', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/HC', 22)
,('THS_HR', NULL, 'Thousand hours', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_HR', 22)
,('MIO_HR', NULL, 'Million hours', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_HR', 22)
,('FTE', NULL, 'Full-time equivalent (FTE)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/FTE', 22)
,('HAB_HC', NULL, 'Inhabitants per ... (head count)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/HAB_HC', 22)
,('HAB_FTE', NULL, 'Inhabitants per ... (full time equivalent)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/HAB_FTE', 22)
,('PCE', NULL, 'Piece', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCE', 22)
,('PER', NULL, 'Person', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PER', 22)
,('PERS', NULL, 'Persons', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PERS', 22)
,('P_KM2', NULL, 'Per square kilometre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/P_KM2', 22)
,('TOTAL', NULL, 'Total', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TOTAL', 22)
,('BAL', NULL, 'Balance', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/BAL', 22)
,('MIO-EUR-SA', NULL, 'Trade value - million of euro - seasonally and working day adjusted', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO-EUR-SA', 22)
,('MIO-EUR-NSA', NULL, 'Trade value - million of euro - not seasonally adjusted', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO-EUR-NSA', 22)
,('IVU-NSA', NULL, 'Unit value index (2015=100) - not seasonally adjusted', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/IVU-NSA', 22)
,('IVOL-SA', NULL, 'Volume index (2015=100) - seasonally and working day adjusted', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/IVOL-SA', 22)
,('IVOL-NSA', NULL, 'Volume index (2015=100) - not seasonally adjusted', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/IVOL-NSA', 22)
,('RT1', NULL, 'Growth rate on previous period (t/t-1)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT1', 22)
,('RT12', NULL, 'Growth rate (t/t-12)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT12', 22)
,('RT1-ABS-SA', NULL, 'Trade value - growth rate (m/m-1) - seasonally and working day adjusted', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT1-ABS-SA', 22)
,('RT12-ABS-NSA', NULL, 'Trade value - growth rate (m/m-12) - not seasonally adjusted', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT12-ABS-NSA', 22)
,('RT1-IVU-NSA', NULL, 'Unit value index (2015=100) - growth rate (m/m-1) - not seasonally adjusted', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT1-IVU-NSA', 22)
,('RT12-IVU-NSA', NULL, 'Unit value index (2015=100) - growth rate (m/m-12) - not seasonally adjusted', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT12-IVU-NSA', 22)
,('RT1-IVOL-SA', NULL, 'Volume index (2015=100) - growth rate (m/m-1) - seasonally and working day adjusted', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT1-IVOL-SA', 22)
,('RT12-IVOL-NSA', NULL, 'Volume index (2015=100) - growth rate (m/m-12) - not seasonally adjusted', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT12-IVOL-NSA', 22)
,('RT4-NSA', NULL, 'Percentage change (t/t-4) - not seasonally adjusted data', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT4-NSA', 22)
,('RT12-NSA', NULL, 'Percentage change (t/t-12) - not seasonally adjusted data', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT12-NSA', 22)
,('RT4', NULL, 'Growth rate on the same quarter in previous year', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT4', 22)
,('PC_EU25', NULL, 'Percentage of EU25 (2004-2006) total', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU25', 22)
,('PC_EU15_PPS_EMP', NULL, 'Percentage of EU15 (1995-2004) total (based on purchasing power standards per employed person)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU15_PPS_EMP', 22)
,('MOVE', NULL, 'Movement', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MOVE', 22)
,('FLIGHT', NULL, 'Flight', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/FLIGHT', 22)
,('MIO_VKM', NULL, 'Million vehicle-kilometres (VKM)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_VKM', 22)
,('THS_VKM', NULL, 'Thousand vehicle-kilometres (VKM)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_VKM', 22)
,('SEAT', NULL, 'Seats and berths', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/SEAT', 22)
,('VES_MOV', NULL, 'Vessel movements', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/VES_MOV', 22)
,('PC_HH_IACCX', NULL, 'Percentage of households without internet access at home', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_HH_IACCX', 22)
,('PC_HH_BROADX', NULL, 'Percentage of households without broadband access', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_HH_BROADX', 22)
,('MIO_EUR_NSA', NULL, 'Million euro (NSA)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_EUR_NSA', 22)
,('TVAL_SA', NULL, 'Trade value in million euro (SA)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TVAL_SA', 22)
,('PCH_M1', NULL, 'Percentage change m/m-1', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_M1', 22)
,('PCH_M1_NSA', NULL, 'Percentage change m/m-1 (NSA)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_M1_NSA', 22)
,('PCH_M1_SA', NULL, 'Percentage change m/m-1 (SA)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_M1_SA', 22)
,('PCH_Q1_NSA', NULL, 'Percentage change q/q-1 (NSA)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_Q1_NSA', 22)
,('PCH_Q4_NSA', NULL, 'Percentage change q/q-4 (NSA)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_Q4_NSA', 22)
,('PCH_M12', NULL, 'Percentage change m/m-12', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_M12', 22)
,('PCH_M12_NSA', NULL, 'Percentage change m/m-12 (NSA)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_M12_NSA', 22)
,('AVG_3Y', NULL, 'Three-year average', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/AVG_3Y', 22)
,('PCH_1Y', NULL, 'Percentage change (t/t-1)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_1Y', 22)
,('PCH_3Y', NULL, 'Percentage change (t/t-3)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_3Y', 22)
,('PCH_5Y', NULL, 'Percentage change (t/t-5)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_5Y', 22)
,('PCH_10Y', NULL, 'Percentage change (t/t-10)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_10Y', 22)
,('PCH_MV12', NULL, 'Percentage change - 12-months average', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_MV12', 22)
,('PC_ENT_WEB', NULL, 'Percentage of the enterprises having a website', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_WEB', 22)
,('PC_ENT_RFID', NULL, 'Percentage of the enterprises using RFID', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_RFID', 22)
,('PC_ETURN', NULL, 'Percentage of turnover from e-commerce', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ETURN', 22)
,('PC_ENT_AEBUY', NULL, 'Percentage of enterprises sending e-commerce orders over the last calendar year', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_AEBUY', 22)
,('PC_ENT_AESELL', NULL, 'Percentage of enterprises receiving e-commerce orders over the last calendar year', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_AESELL', 22)
,('PC_ENT_ADE', NULL, 'Percentage of enterprises using ADE', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_ADE', 22)
,('PC_ENT_SISC', NULL, 'Percentage of enterprises sharing information electronically on the supply chain management', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_SISC', 22)
,('PC_ENT_SECPOL', NULL, 'Percentage of enterprises with an ICT security policy', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_SECPOL', 22)
,('PC_IND_SCSOFT', NULL, 'Percentage of individuals who used security software or tool', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_SCSOFT', 22)
,('PC_IND_SCUAVX', NULL, 'Percentage of individuals who dont update their security products', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_SCUAVX', 22)
,('TIME_SP', NULL, 'Time spent (hh:mm)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TIME_SP', 22)
,('PTP_TIME', NULL, 'Participation time (hh:mm)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PTP_TIME', 22)
,('PTP_RT', NULL, 'Participation rate (%)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PTP_RT', 22)
,('CAP_1000T_Y', NULL, 'Annual capacity/inputs in 1000T', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/CAP_1000T_Y', 22)
,('PC_ENT_ECOM', NULL, 'Percentage of enterprises which sent/received orders via any computer networks', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_ECOM', 22)
,('PC_GDP_3Y', NULL, 'Percentage of GDP - three-year average', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_GDP_3Y', 22)
,('PCH_WRL_5Y', NULL, 'Percentage of world total - 5-year change', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_WRL_5Y', 22)
,('PC_IND_IUMC', NULL, 'Percentage of individuals who have used a portable computer to access internet', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_IUMC', 22)
,('PC_IND_IUMD', NULL, 'Percentage of individuals who used a handheld device or portable computer to access internet', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_IUMD', 22)
,('PC_IND_IUMDX', NULL, 'Percentage of individuals who didnt use a handheld device or portable computer to access internet', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_IUMDX', 22)
,('PC_IND_IUHD', NULL, 'Percentage of individuals who used a handheld device to access internet', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_IUHD', 22)
,('PC_EMP_IUSE', NULL, 'Percentage of persons employed using a computer with access to the www', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EMP_IUSE', 22)
,('PC_EMP_PMD', NULL, 'Percentage of persons employed working in enterprises which provide mobile devices', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EMP_PMD', 22)
,('PC_ENT_PMD', NULL, 'Percentage of enterprises providing to persons employed portable devices that allow a mobile connection to the internet', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_PMD', 22)
,('PC_AWSVAL', NULL, 'Percentage of web sales', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_AWSVAL', 22)
,('PC_EMP_CUSE2', NULL, 'Percentage of persons employed working in enterprises which use computers', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EMP_CUSE2', 22)
,('P_HHAB', NULL, 'Per hundred inhabitants', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/P_HHAB', 22)
,('P_THAB', NULL, 'Per thousand inhabitants', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/P_THAB', 22)
,('P_HTHAB', NULL, 'Per hundred thousand inhabitants', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/P_HTHAB', 22)
,('PCH_WRL_1Y', NULL, 'Percentage of world total - 1-year change', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_WRL_1Y', 22)
,('PC_OECD', NULL, 'Percentage of OECD total', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_OECD', 22)
,('PCH_OECD_5Y', NULL, 'Percentage of OECD total - 5-year change', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_OECD_5Y', 22)
,('MPPS_KM2', NULL, 'Million purchasing power standards (PPS) per square kilometre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MPPS_KM2', 22)
,('EUR_KGOE', NULL, 'Euro per kilogram of oil equivalent (KGOE)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/EUR_KGOE', 22)
,('PC_IGRTX', NULL, 'Percentage of individuals who have used internet but not for sending filled forms to public authorities', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IGRTX', 22)
,('PC_IGRTX_NAPX', NULL, 'Percentage of individuals who have used internet but not for sending filled forms to public authorities although they had to', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IGRTX_NAPX', 22)
,('PPS_HAB_KP00', NULL, 'Purchasing power standard (PPS) per inhabitant at constant 2000 prices', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PPS_HAB_KP00', 22)
,('O2_TD', NULL, 'Tonnes of O2 per day', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/O2_TD', 22)
,('PC_GEXP', NULL, 'Percentage of government expenditure', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_GEXP', 22)
,('PC_HC', NULL, 'Percentage based on head count (HC)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_HC', 22)
,('PC_FTE', NULL, 'Percentage based on full-time equivalents (FTE)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_FTE', 22)
,('TSWU', NULL, 'Tonnes of separative work units', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TSWU', 22)
,('THM', NULL, 'Tonnes of heavy metal', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THM', 22)
,('GWD_THM', NULL, 'Gigawatt-days per tonne of heavy metal', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/GWD_THM', 22)
,('PC_IND_IUGOV12', NULL, 'Percentage of e-government users', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_IUGOV12', 22)
,('P_MHAB', NULL, 'Per million inhabitants', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/P_MHAB', 22)
,('PC_EU28', NULL, 'Percentage of EU28 (2013-2020) total', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU28', 22)
,('PC_EU28_EUR_HAB', NULL, 'Percentage of EU28 (2013-2020) total (based on euro per inhabitant)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU28_EUR_HAB', 22)
,('PC_EU28_PPS_HAB', NULL, 'Percentage of EU28 (2013-2020) total (based on purchasing power standards per inhabitant)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU28_PPS_HAB', 22)
,('PC_EU28_PPS_EMP', NULL, 'Percentage of EU28 (2013-2020) total (based on purchasing power standards per employed person)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU28_PPS_EMP', 22)
,('TD', NULL, 'Tonnes per day', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TD', 22)
,('PC_GBA', NULL, 'Percentage of total GBAORD', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_GBA', 22)
,('SEI', NULL, 'Shannon evenness index', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/SEI', 22)
,('SDI', NULL, 'Shannon diversity index', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/SDI', 22)
,('THS_M2', NULL, 'Thousand square metres', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_M2', 22)
,('THS_PER', NULL, 'Thousand persons', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_PER', 22)
,('PC_EU28_MEUR', NULL, 'Percentage of EU28 (2013-2020) total (based on million euro)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU28_MEUR', 22)
,('PC_EU28_MPPS', NULL, 'Percentage of EU28 (2013-2020) total (based on million purchasing power standards)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU28_MPPS', 22)
,('PC_EA_MEUR', NULL, 'Percentage of euro area total (based on million euro)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EA_MEUR', 22)
,('PC_EA18_MEUR', NULL, 'Percentage of EA18 (2014) total (based on million euro)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EA18_MEUR', 22)
,('PC_EA17_MEUR', NULL, 'Percentage of EA17 (2011-2013) total (based on million euro)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EA17_MEUR', 22)
,('PC_EA16_MEUR', NULL, 'Percentage of EA16 (2009-2010) total (based on million euro)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EA16_MEUR', 22)
,('PC_EA12_MEUR', NULL, 'Percentage of EA12 (2001-2006) total (based on million euro)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EA12_MEUR', 22)
,('PC_EA18_MPPS', NULL, 'Percentage of EA18 (2014) total (based on million purchasing power standards)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EA18_MPPS', 22)
,('PC_EA17_MPPS', NULL, 'Percentage of EA17 (2011-2013) total (based on million purchasing power standards)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EA17_MPPS', 22)
,('PC_EA16_MPPS', NULL, 'Percentage of EA16 (2009-2010) total (based on million purchasing power standards)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EA16_MPPS', 22)
,('PC_STU', NULL, 'Percentage of total tertiary students', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_STU', 22)
,('PC_FSTU', NULL, 'Percentage of total foreign tertiary students', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_FSTU', 22)
,('PC_Y25-29', NULL, 'Percentage of total population aged 25-29', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_Y25-29', 22)
,('PC_Y20-29', NULL, 'Percentage of total population aged 20-29', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_Y20-29', 22)
,('PC_TOT_PER', NULL, 'Percentage of total (based on persons)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_TOT_PER', 22)
,('PC_TOT_HW', NULL, 'Percentage of total (based on hours worked)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_TOT_HW', 22)
,('PCH_PRE_PER', NULL, 'Percentage change on previous period (based on persons)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_PRE_PER', 22)
,('PCH_PRE_HW', NULL, 'Percentage change on previous period (based on hours worked)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_PRE_HW', 22)
,('PCH_SM_PER', NULL, 'Percentage change compared to same period in previous year (based on persons)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_SM_PER', 22)
,('PCH_SM_HW', NULL, 'Percentage change compared to same period in previous year (based on hours worked)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_SM_HW', 22)
,('PCH_SM_JOB', NULL, 'Percentage change compared to same period in previous year (based on jobs)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_SM_JOB', 22)
,('PCH_SM_FTE', NULL, 'Percentage change compared to same period in previous year (based on full-time equivalents)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_SM_FTE', 22)
,('RT_UNE', NULL, 'Unemployment rate', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT_UNE', 22)
,('HW', NULL, 'Hours worked', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/HW', 22)
,('THS_HW', NULL, 'Thousand hours worked', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_HW', 22)
,('THS_JOB', NULL, 'Thousand jobs', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_JOB', 22)
,('THS_FTE', NULL, 'Thousand full-time equivalents (FTE)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_FTE', 22)
,('VKM', NULL, 'Vehicle-kilometre (VKM)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/VKM', 22)
,('PPS_KGOE', NULL, 'Purchasing power standard (PPS) per kilogram of oil equivalent', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PPS_KGOE', 22)
,('PPS_M3', NULL, 'Purchasing power standard (PPS) per cubic metre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PPS_M3', 22)
,('G', NULL, 'Gram', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/G', 22)
,('PAS', NULL, 'Passenger', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PAS', 22)
,('THS_PAS', NULL, 'Thousand passengers', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_PAS', 22)
,('THS_PASF', NULL, 'Thousand passengers (excluding cruise passengers)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_PASF', 22)
,('THS_PASC', NULL, 'Thousand cruise passengers starting and ending a cruise', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_PASC', 22)
,('THS_PASE', NULL, 'Thousand cruise passengers on excursion', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_PASE', 22)
,('PC_ENT_CC', NULL, 'Percentage of enterprises buying CC services', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_CC', 22)
,('PC_ENT_CCX', NULL, 'Percentage of enterprises not buying CC services', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_CCX', 22)
,('PC_ENT_INV3SBG', NULL, 'Percentage of enterprises sending invoices B2BG', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_INV3SBG', 22)
,('PC_ENT_RFID1', NULL, 'Percentage of enterprises using RFID (as of 2014)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_RFID1', 22)
,('PC_IND_CC_CCS', NULL, 'Percentage of individuals who used internet and cloud services for file saving or sharing', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_CC_CCS', 22)
,('PC_IND_CC_CCSX', NULL, 'Percentage of individuals who used internet but not cloud services', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_CC_CCSX', 22)
,('RT_PRE', NULL, 'Growth rate on previous period (t/t-1)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT_PRE', 22)
,('RT_PRE_GT', NULL, 'Growth rate on previous period (t/t-1) for gross tonnage of vessels', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT_PRE_GT', 22)
,('RT_PRE_NR', NULL, 'Growth rate on previous period (t/t-1) for number of vessels', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT_PRE_NR', 22)
,('INX', NULL, 'Index', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/INX', 22)
,('PC_Y_LT60', NULL, 'Percentage of total population aged less than 60', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_Y_LT60', 22)
,('INX_Q', NULL, 'Quarterly index', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/INX_Q', 22)
,('INX_A_AVG', NULL, 'Annual average index', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/INX_A_AVG', 22)
,('P_BERD', NULL, 'Per billion euro of business enterprise expenditure on R&D (BERD)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/P_BERD', 22)
,('P_GERD', NULL, 'Per billion euro of gross domestic expenditure on R&D (GERD)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/P_GERD', 22)
,('RCH_M', NULL, 'Monthly rate of change', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RCH_M', 22)
,('RCH_Q', NULL, 'Quarterly rate of change', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RCH_Q', 22)
,('RCH_A', NULL, 'Annual rate of change', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RCH_A', 22)
,('RCH_A_AVG', NULL, 'Annual average rate of change', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RCH_A_AVG', 22)
,('HAB_P', NULL, 'Inhabitants per ...', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/HAB_P', 22)
,('HC_HTHAB', NULL, 'Head count per hundred thousand inhabitants', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/HC_HTHAB', 22)
,('FTE_HTHAB', NULL, 'Full time equivalent per hundred thousand inhabitants', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/FTE_HTHAB', 22)
,('RCH_MV12MAVR', NULL, 'Moving 12 months average rate of change', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RCH_MV12MAVR', 22)
,('KGOE_TEUR', NULL, 'Kilograms of oil equivalent (KGOE) per thousand euro', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KGOE_TEUR', 22)
,('RTG', NULL, 'Rating (0-10)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RTG', 22)
,('PPCH_3Y', NULL, 'Percentage point change (t/t-3)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PPCH_3Y', 22)
,('PC_UP95', NULL, 'Percentage of total population - upper boundary of the 95% confidence interval', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_UP95', 22)
,('PC_LW95', NULL, 'Percentage of total population - lower boundary of the 95% confidence interval', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_LW95', 22)
,('PC_GVA', NULL, 'Percentage of gross value added (GVA)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_GVA', 22)
,('PC_ENT_AWSELL', NULL, 'Percentage of enterprises with web sales', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_AWSELL', 22)
,('PC_ENT_AWSELLX', NULL, 'Percentage of enterprises without web sales', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_AWSELLX', 22)
,('RT_INC', NULL, 'Incidence rate', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT_INC', 22)
,('RT_SINC', NULL, 'Standardised incidence rate', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT_SINC', 22)
,('GDP_BEUR', NULL, 'Nominal GDP in billion euro', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/GDP_BEUR', 22)
,('P_MACT', NULL, 'Per million of active population', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/P_MACT', 22)
,('PC_TSCO', NULL, 'Percentage of total revenues from taxes and social contributions (including imputed social contributions)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_TSCO', 22)
,('PC_TSCO_X_ISCO', NULL, 'Percentage of total revenues from taxes and social contributions (excluding imputed social contributions)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_TSCO_X_ISCO', 22)
,('HLD', NULL, 'Holding', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/HLD', 22)
,('MEUR_KP00', NULL, 'Million euro (at constant 2000 prices)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MEUR_KP00', 22)
,('THS_SEAT', NULL, 'Thousand seats', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_SEAT', 22)
,('KM_TKM2', NULL, 'Kilometres per thousand square kilometres', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KM_TKM2', 22)
,('MEUR_NSA', NULL, 'Million euro (NSA)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MEUR_NSA', 22)
,('MEUR_KP11', NULL, 'Million euro (at constant 2011 prices)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MEUR_KP11', 22)
,('MEUR_KP_PRE', NULL, 'Million euro (at prices of the previous year)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MEUR_KP_PRE', 22)
,('GDP_HAB', NULL, 'GDP per capita', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/GDP_HAB', 22)
,('PC_GNI', NULL, 'Percentage of gross national income (GNI)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_GNI', 22)
,('PC_PEXP', NULL, 'Percentage of total public expenditure', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_PEXP', 22)
,('CFU', NULL, 'Colony-forming unit (CFU)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/CFU', 22)
,('KGOE', NULL, 'Kilogram of oil equivalent (KGOE)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KGOE', 22)
,('TOE', NULL, 'Tonnes of oil equivalent (TOE)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TOE', 22)
,('TKM', NULL, 'Tonne-kilometre (TKM)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TKM', 22)
,('HL', NULL, 'Hectolitre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/HL', 22)
,('PPCS_HAB_EU', NULL, 'Purchasing power consumption standards per inhabitant in percentage of the EU average', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PPCS_HAB_EU', 22)
,('THS_TD', NULL, 'Thousand tonnes per day', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_TD', 22)
,('PM', NULL, 'Per mille', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PM', 22)
,('PC_UAA', NULL, 'Percentage of total utilised agricultural area', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_UAA', 22)
,('PC_IND_BUY3', NULL, 'Percentage of individuals who purchased online in the last 3 months', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_BUY3', 22)
,('RK', NULL, 'Rank', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RK', 22)
,('THS_TEUKM', NULL, 'Thousand TEU-kilometres', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_TEUKM', 22)
,('THS_KW', NULL, 'Thousand kilowatts', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_KW', 22)
,('THS_JRNY', NULL, 'Thousand journeys', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_JRNY', 22)
,('THS_BTO', NULL, 'Thousand transport operations', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_BTO', 22)
,('THS_TRKM', NULL, 'Thousand train-kilometres', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_TRKM', 22)
,('THS_VESKM', NULL, 'Thousand vessel-kilometres', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_VESKM', 22)
,('PC_ENT_SECPOL1', NULL, 'Percentage of enterprises with an ICT security policy (as of 2015)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_SECPOL1', 22)
,('TCO2E', NULL, 'Tonnes of CO2 equivalent', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TCO2E', 22)
,('MEUR_KP05', NULL, 'Million euro (at constant 2005 prices)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MEUR_KP05', 22)
,('MNAC_KP05', NULL, 'Million units of national currency at constant 2005 prices', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MNAC_KP05', 22)
,('PCH_M1_SCA', NULL, 'Percentage change m/m-1 (SCA)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_M1_SCA', 22)
,('PCH_M12_CA', NULL, 'Percentage change m/m-12 (CA)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_M12_CA', 22)
,('PCH_Q1_SCA', NULL, 'Percentage change q/q-1 (SCA)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_Q1_SCA', 22)
,('PCH_Q4_CA', NULL, 'Percentage change q/q-4 (CA)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_Q4_CA', 22)
,('RT1-SCA', NULL, 'Percentage change (t/t-1) - seasonally and calendar adjusted data', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT1-SCA', 22)
,('NR_ENT', NULL, 'Number of enterprises', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/NR_ENT', 22)
,('MIO_EUR_SCA', NULL, 'Million euro (SCA)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_EUR_SCA', 22)
,('SUM_4Q', NULL, 'Sum of the last 4 quarters', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/SUM_4Q', 22)
,('RT_R4Q', NULL, 'Rolling 4-quarter growth rate', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT_R4Q', 22)
,('TCO2E_HAB', NULL, 'Tonnes of CO2 equivalent per capita', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TCO2E_HAB', 22)
,('THS_L', NULL, 'Thousand litres', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_L', 22)
,('G_HAB', NULL, 'Grams per capita', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/G_HAB', 22)
,('SGM_ESU', NULL, 'Standard gross margin (SGM) in economic size unit (ESU)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/SGM_ESU', 22)
,('PC_S', NULL, 'Standardised percentage', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_S', 22)
,('PC_ENT_FIXBB', NULL, 'Percentage of enterprises using a fixed broadband connection', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_FIXBB', 22)
,('HR_SAL', NULL, 'Hours per employee', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/HR_SAL', 22)
,('RCH_A_C', NULL, 'Compound annual rate of change', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RCH_A_C', 22)
,('EUR_TOE', NULL, 'Euro per tonne of oil equivalent (TOE)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/EUR_TOE', 22)
,('PC_ENT_ADS', NULL, 'Percentage of enterprises using internet ads', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_ADS', 22)
,('MEUR_KP10', NULL, 'Million euro (at constant 2010 prices)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MEUR_KP10', 22)
,('MNAC_KP10', NULL, 'Million units of national currency at constant 2010 prices', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MNAC_KP10', 22)
,('PC_IND_IUG_TV', NULL, 'Percentage of individuals who used the internet on a smart TV (directly connected to the internet)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_IUG_TV', 22)
,('PC_EMP_PMD1', NULL, 'Percentage of persons employed working in enterprises which provide mobile devices (as of 2016)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EMP_PMD1', 22)
,('EUR_BGDP', NULL, 'Euro per billion GDP', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/EUR_BGDP', 22)
,('EUR_HAB_KP10', NULL, 'Euro per inhabitant (at constant 2010 prices)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/EUR_HAB_KP10', 22)
,('PPS_BGDP', NULL, 'Purchasing power standard (PPS) per billion GDP', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PPS_BGDP', 22)
,('PC_ENT_PMD1', NULL, 'Percentage of enterprises providing to persons employed portable devices that allow a mobile connection to the internet (as of 2016)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_PMD1', 22)
,('AVG_A', NULL, 'Annual average', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/AVG_A', 22)
,('MTCO2E', NULL, 'Million tonnes of CO2 equivalent', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MTCO2E', 22)
,('PC_ENT_SM', NULL, 'Percentage of enterprises using social media', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_SM', 22)
,('PPS_HH', NULL, 'Purchasing power standard (PPS) per household', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PPS_HH', 22)
,('P_HH', NULL, 'Per household', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/P_HH', 22)
,('PC_DI', NULL, 'Percentage of disposable income', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_DI', 22)
,('PC_LSU', NULL, 'Percentage of total livestock units', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_LSU', 22)
,('PC_ENT_BD', NULL, 'Percentage of enterprises analysing big data', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_BD', 22)
,('EUR_AE', NULL, 'Euro per adult equivalent', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/EUR_AE', 22)
,('EUR_HH', NULL, 'Euro per household', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/EUR_HH', 22)
,('NAC_AE', NULL, 'National currency per adult equivalent', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/NAC_AE', 22)
,('NAC_HH', NULL, 'National currency per household', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/NAC_HH', 22)
,('PPS_AE', NULL, 'Purchasing power standard (PPS) per adult equivalent', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PPS_AE', 22)
,('KG_HA', NULL, 'Kilograms per hectare', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KG_HA', 22)
,('PC_ELF', NULL, 'Percentage of extended labour force', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ELF', 22)
,('PC_ENT_AWSEU', NULL, 'Percentage of enterprises with web sales to other EU countries', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_AWSEU', 22)
,('PC_IND_BFFOR', NULL, 'Percentage of individuals who purchased online from sellers from other countries (EU or non-EU)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_BFFOR', 22)
,('MIO_PER', NULL, 'Million persons', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_PER', 22)
,('PC_WMN', NULL, 'Percentage of women', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_WMN', 22)
,('PPS_HAB_EU28', NULL, 'Purchasing power standard (PPS) per inhabitant in percentage of the EU28 (2013-2020) average', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PPS_HAB_EU28', 22)
,('DEGC', NULL, 'Degree Celsius', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/DEGC', 22)
,('PH', NULL, 'pH value', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PH', 22)
,('PC_SAL', NULL, 'Percentage of employees', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_SAL', 22)
,('PC_SAL_TEMP', NULL, 'Percentage of employees with a temporary job', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_SAL_TEMP', 22)
,('M2_HAB', NULL, 'Square metres per capita', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/M2_HAB', 22)
,('KM2_HAB', NULL, 'Square kilometres per capita', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KM2_HAB', 22)
,('MCG_M3', NULL, 'Micrograms per cubic metre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MCG_M3', 22)
,('PC_DT', NULL, 'Distance to target in percentage', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_DT', 22)
,('RT_PRE_EUR', NULL, 'Growth rate on previous period (t/t-1) for values in euro', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT_PRE_EUR', 22)
,('RT_PRE_NAC', NULL, 'Growth rate on previous period (t/t-1) for values in national currency', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT_PRE_NAC', 22)
,('M_KM2', NULL, 'Metres per square kilometre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/M_KM2', 22)
,('KM_THAB', NULL, 'Kilometres per thousand inhabitants', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KM_THAB', 22)
,('PC_RIMG', NULL, 'Percentage of total recent immigrants', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_RIMG', 22)
,('PC_ENT_P3D', NULL, 'Percentage of enterprises with 3D printing', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_P3D', 22)
,('PC_ENT_RBTS', NULL, 'Percentage of enterprises using service robots', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_RBTS', 22)
,('PC_IND_IUP2P_WRK', NULL, 'Percentage of individuals who have obtained paid work by using an intermediary website or apps', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_IUP2P_WRK', 22)
,('PC_IND_MPP', NULL, 'Percentage of individuals who use a smartphone for private purposes', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_MPP', 22)
,('PC_IND_ILT12_SSF', NULL, 'Percentage of employees and self-employed who used internet within the last year', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_ILT12_SSF', 22)
,('PC_IND_WH', NULL, 'Percentage of individuals working from home', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_WH', 22)
,('PC_IND_WM', NULL, 'Percentage of individuals working at an external site or on the move', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_WM', 22)
,('THS_TY', NULL, 'Thousand tonnes per year', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/THS_TY', 22)
,('MIO_M3D', NULL, 'Million cubic metres per day', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MIO_M3D', 22)
,('BN_M3Y', NULL, 'Billion cubic metres per year', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/BN_M3Y', 22)
,('MWH', NULL, 'Megawatt-hour', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MWH', 22)
,('KJ_M3', NULL, 'Kilojoule per cubic metre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KJ_M3', 22)
,('MJ_T_GCV', NULL, 'Megajoule per tonne (gross calorific value - GCV)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MJ_T_GCV', 22)
,('MJ_T_NCV', NULL, 'Megajoule per tonne (net calorific value - NCV)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MJ_T_NCV', 22)
,('KJ_M3_NCV', NULL, 'Kilojoule per cubic metre (net calorific value - NCV)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KJ_M3_NCV', 22)
,('KJ_M3_GCV', NULL, 'Kilojoule per cubic metre (gross calorific value - GCV)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KJ_M3_GCV', 22)
,('PCH_Q4_SCA', NULL, 'Percentage change q/q-4 (SCA)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_Q4_SCA', 22)
,('KGOE_TEUR_PPS', NULL, 'Kilograms of oil equivalent (KGOE) per thousand euro in purchasing power standards (PPS)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KGOE_TEUR_PPS', 22)
,('TOE_MEUR', NULL, 'Tonnes of oil equivalent (TOE) per million euro', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TOE_MEUR', 22)
,('RT_M_DIF', NULL, 'Monthly rate differences between HICP and HICP at constant taxes', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RT_M_DIF', 22)
,('KGOE_HAB', NULL, 'Kilograms of oil equivalent (KGOE) per capita', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KGOE_HAB', 22)
,('TOE_HAB', NULL, 'Tonnes of oil equivalent (TOE) per capita', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TOE_HAB', 22)
,('KJ', NULL, 'Kilojoule', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/KJ', 22)
,('MJ', NULL, 'Megajoule', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MJ', 22)
,('MJ_HAB', NULL, 'Megajoule per capita', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MJ_HAB', 22)
,('GJ', NULL, 'Gigajoule', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/GJ', 22)
,('GJ_HAB', NULL, 'Gigajoule per capita', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/GJ_HAB', 22)
,('TJ_HAB', NULL, 'Terajoule per capita', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TJ_HAB', 22)
,('PER_KM2', NULL, 'Persons per square kilometre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PER_KM2', 22)
,('RAT', NULL, 'Ratio', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/RAT', 22)
,('MG_L', NULL, 'Milligrams per litre', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MG_L', 22)
,('EUR_HAB_EU27_2020', NULL, 'Euro per inhabitant in percentage of the EU27 (from 2020) average', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/EUR_HAB_EU27_2020', 22)
,('PC_EU27_2020', NULL, 'Percentage of EU27 (from 2020) total', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU27_2020', 22)
,('PC_EU27_2007', NULL, 'Percentage of EU27 (2007-2013) total', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU27_2007', 22)
,('PC_EU27_2020_EUR_HAB', NULL, 'Percentage of EU27 (from 2020) total (based on euro per inhabitant)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU27_2020_EUR_HAB', 22)
,('PC_EU27_2007_EUR_HAB', NULL, 'Percentage of EU27 (2007-2013) total (based on euro per inhabitant)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU27_2007_EUR_HAB', 22)
,('PC_EU27_2020_PPS_HAB', NULL, 'Percentage of EU27 (from 2020) total (based on purchasing power standards per inhabitant)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU27_2020_PPS_HAB', 22)
,('PC_EU27_2007_PPS_HAB', NULL, 'Percentage of EU27 (2007-2013) total (based on purchasing power standards per inhabitant)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU27_2007_PPS_HAB', 22)
,('PC_EU27_2020_PPS_EMP', NULL, 'Percentage of EU27 (from 2020) total (based on purchasing power standards per employed person)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU27_2020_PPS_EMP', 22)
,('PC_EU27_2007_PPS_EMP', NULL, 'Percentage of EU27 (2007-2013) total (based on purchasing power standards per employed person)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU27_2007_PPS_EMP', 22)
,('PC_EU27_2020_MEUR', NULL, 'Percentage of EU27 (from 2020) total (based on million euro)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU27_2020_MEUR', 22)
,('PC_EU27_2007_MEUR', NULL, 'Percentage of EU27 (2007-2013) total (based on million euro)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU27_2007_MEUR', 22)
,('PC_EU27_2020_MPPS', NULL, 'Percentage of EU27 (from 2020) total (based on million purchasing power standards)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU27_2020_MPPS', 22)
,('PC_EU27_2007_MPPS', NULL, 'Percentage of EU27 (2007-2013) total (based on million purchasing power standards)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_EU27_2007_MPPS', 22)
,('MEUR_HAB', NULL, 'Million euro per inhabitant', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/MEUR_HAB', 22)
,('PC_ENT_BDA', NULL, 'Percentage of enterprises analysing big data internally or externally', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_BDA', 22)
,('PC_ENT_BDAAM', NULL, 'Percentage of enterprises analysing big data internally using any method', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_BDAAM', 22)
,('PC_ENT_IOT', NULL, 'Percentage of enterprises using Internet of Things', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_IOT', 22)
,('PC_ENT_AWS_CMP', NULL, 'Percentage of enterprises with web sales via e-commerce marketplaces', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_AWS_CMP', 22)
,('PC_ENT_IUSE', NULL, 'Percentage of enterprises where persons employed have access to the internet', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_IUSE', 22)
,('PC_ENT_ITSPVAC2', NULL, 'Percentage of enterprises with hard-to-fill vacancies for jobs requiring ICT specialist skills (as of 2020)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_ENT_ITSPVAC2', 22)
,('PC_IND_BHHS', NULL, 'Percentage of individuals who purchased online household services', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_BHHS', 22)
,('PC_IND_BPG_ANY', NULL, 'Percentage of individuals who purchased online physical goods', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_BPG_ANY', 22)
,('PC_IND_BRA', NULL, 'Percentage of individuals who rented accommodation online from an enterprise or a private person', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_BRA', 22)
,('PC_IND_BTPS', NULL, 'Percentage of individuals who purchased online transport service from a transport enterprise or a private person', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_BTPS', 22)
,('PC_IND_IOT_BDKX', NULL, 'Percentage of individuals who have not used any internet-connected device or systems although they knew about them', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_IOT_BDKX', 22)
,('PC_IND_IOT_DX', NULL, 'Percentage of individuals who have not used any internet-connected devices or systems', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_IOT_DX', 22)
,('PC_IND_MPP1', NULL, 'Percentage of individuals who use a smartphone for private purposes (3 months)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_IND_MPP1', 22)
,('PC_Y', NULL, 'Percentage in the year', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PC_Y', 22)
,('TJ_NCV', NULL, 'Terajoule (net calorific value - NCV)', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TJ_NCV', 22)
,('TVAL_MEUR', NULL, 'Trade value in million euro', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/TVAL_MEUR', 22)
,('PCH_LV_M_16-19', NULL, 'Percentage change of the current month compared to the lowest value for the corresponding month in the period 2016-2019', 'http://dd.eionet.europa.eu/vocabulary/eurostat/unit/PCH_LV_M_16-19', 22);


SELECT setval('vocabulary_id_seq', max(id)) FROM vocabulary;